[package]
name = "advent-of-code-2023"
version = "0.1.0"
authors = ["Graeme Robertson <grobertson@microsoft.com>"]
edition = "2021"

[dependencies]
num-integer = "0.1.45"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
structopt = "0.3.26"
